### ISSUE TITLE
Call `scout:import` in controller: There are no commands defined in the "scout" namespace.

### ISSUE THREAD

**Issue by windows1087** [laravel/scout#100]
If i run

```
Artisan::call('scout:import')
```

in an Controller or route closure, following error came:

```
CommandNotFoundException in Application.php line 490: There are no commands defined in the "scout" namespace.
```

The command works great in the CLI, but not in an controller.

**Comment by windows1087** [comment]
I the `ScoutServiceProvider.php` file there is this line:

```php
if ($this->app->runningInConsole()) {
            $this->commands([
                ImportCommand::class,
                FlushCommand::class,
            ]);

            $this->publishes([
                __DIR__.'/../config/scout.php' => config_path('scout.php'),
            ]);
        }
```

So it register only this commands in `cli mode`. Is there an reason for this?

**Comment by MikeMnD** [comment]
I've got the same question. Cause i made: 

`Route::get('console/search:create-index', function () {
    Artisan::call('scout:import App\\\\Models\\\\News');
});`

**Comment by julienbourdeau** [comment]
I think it's not allowed because it could timeout so it has to be ran in command mode.

**Comment by yateseyb** [comment]
I managed to find a solution by making the custom method a subclass of the ImportCommand class. No need for a handle method in this.

class RefreshSearch extends \Laravel\Scout\Console\ImportCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'search.refresh {model}';

**Comment by yateseyb** [comment]
I managed to find a solution by making the custom method a subclass of the ImportCommand class. No need for a handle method in this.
```
class RefreshSearch extends \Laravel\Scout\Console\ImportCommand

{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'search.refresh {model}';

 
```

**Comment by spacemudd** [comment]
@windows1087 Dude, I was scratching my head for the past hour as to why Artisan isn't finding `tntsearch` namespace if I'm executing the same command through a controller.

@julienbourdeau +1, the proper way is to offload the import job to a queue and have it be processed in the background.

Anyways, for my use case, I'm 100% dealing with less than 5k records every import/refresh and because I'm working locally, I'm fine in waiting seconds / hogging up the web server.

What I basically did was to override the `TNTSearchScoutServiceProvider` boot() method. 

1. Create a `TNTSearchScoutServiceProvider` in App\Providers, so,

```
<?php

namespace App\Providers;

use TeamTNT\Scout\Console\ImportCommand;
use Laravel\Scout\EngineManager;
use TeamTNT\TNTSearch\TNTSearch;
use TeamTNT\Scout\Engines\TNTSearchEngine;

class TNTSearchScoutServiceProvider extends \TeamTNT\Scout\TNTSearchScoutServiceProvider
{
    public function boot()
    {
        $this->app[EngineManager::class]->extend('tntsearch', function ($app) {
            $tnt = new TNTSearch();

            $driver = config('database.default');
            $config = config('scout.tntsearch') + config("database.connections.{$driver}");

            $tnt->loadConfig($config);
            $tnt->setDatabaseHandle(app('db')->connection()->getPdo());

            $this->setFuzziness($tnt);
            $this->setAsYouType($tnt);

            return new TNTSearchEngine($tnt);
        });

        //if ($this->app->runningInConsole()) {
        //    $this->commands([
        //        ImportCommand::class,
        //    ]);
        //}

        // To allow us run commands if we're not running in the console
        $this->commands([
            ImportCommand::class,
        ]);
    }
}

```

2. Place your new Provider class in your `app.php` config file, so,

```
'providers' => [
    /*
     * Application Service Providers...
     */
    \App\Providers\TNTSearchScoutServiceProvider::class,
];
```

3. Call the command from the a `Job` class (preferably so when you have a queue driver, you can ditch the temporarily created service provider)... or call it from a controller (bad for reasons @julienbourdeau  pointed out).

`Artisan::call('tntsearch:import', ['model' => 'App\Models\Product']);`

**Comment by driesvints** [comment]
Closing this issue because it's already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue.
