### ISSUE TITLE
Custom query scope

### ISSUE THREAD

**Issue by joostvdspeld** [laravel/scout#140]
When I use the laravel scout search() method on my model, my custom created scope query doesn't work. Is there a way how to use both?

Thanks

**Comment by Kovah** [comment]
I would like to see support for this too.

**Comment by mohitpanjwani** [comment]
Looking for the same thing actually.  I think it's a much needed feature.

**Comment by DMeganoski** [comment]
Well, I had written a few paragraphs about why this would be difficult to implement, but in retrospect it would not be that difficult as long as there was the understanding that the ```$query``` parameter is an instance of ```\Laravel\Scout\Builder``` and not ```Illuminate\Database\Eloquent\Builder```.

What you could do is extend the builder class (and override the search function to use it instead), and add magic methods to your custom builder to check for your scope function on the model. If the scope function exists, pass the custom build class through the scope function before returning it from your search function. A few extra files and lines but you could get back your easy to use and aesthetically pleasing scope methods.

**Comment by anasred** [comment]
i'm looking for the same.

**Comment by FinucaneDesign** [comment]
@DMeganoski Would your work around allow for a user to search their own records instead of every record in the index.  For example if Posts has a user_id field could the Scout\Builder strictly enforce all of the returned records belong to that user?

**Comment by DMeganoski** [comment]
If what you are asking is as simple as I think, yes, that would work. 

I would have to say implementing this yourself would probably be more work than just adding the 'wheres' inline, though it would look better.

It has been a while since I've messed with scout and it took me a few minutes to remember what I was even talking about above.

but yea override search function (or whole searchable trait) return your custom builder and use the `__call($method)` magic method to search for a function named `'scope . camel_case($method)` and if it exists, pass the current query through it and return it.

Then, `Post::serach($term)->own()->get()` would call `function scopeOwn($query)` on the post model, however $query would be your custom builder, not eloquent builder as it normally would be with scopes, and what you can do with it is very limited, but should mostly be backwards-compatible with eloquent as well.

**Comment by gregorskii** [comment]
+1

**Comment by iget-master** [comment]
This is a very frustrating issue. :-1:

**Comment by skalero01** [comment]
We are in 2018 and there isnt any support for this yet? Is this package in develop?

**Comment by taylorotwell** [comment]
@skalero01 YOU can contribute to Scout anytime you want. Stop complaining.
