### ISSUE TITLE
Support count() method

### ISSUE THREAD

**Issue by guoyunhe** [laravel/scout#164]
Sometimes, it is useful to show users how many search results have been found. However, the count() function, which is used in Laravel QueryBuilder, doesn't exist in Scout QueryBuilder. It will be wonderful to have it.

Thanks!

**Comment by julienbourdeau** [comment]
Hi @guoyunhe,

I'm not sure why you need count in the builder. Why can't you use `count()` on the collection?

```php
Model::search($request->search)->get()->count();
```

Please provide more details if I didn't get what you're trying to do.

**Comment by guoyunhe** [comment]
@julienbourdeau Using collection means you have to pull all data to PHP. If here are thousands of search results, it will cause huge memory usage and even cause the thread crash. That is why I would need a count() function in query builder. It is the same reason why MySQL and Laravel QueryBuilder do provide count(). It just return a little data you need, rather than pull everything.

**Comment by joseluisq** [comment]
:+1:

**Comment by julienbourdeau** [comment]
@guoyunhe Yes of course, I didn't think it through. I open a PR #183, any comment is welcomed.

**Comment by julienbourdeau** [comment]
Laravel Scout 3.0.5 added `Macroable` capability to the builder, it can easily be achieved.

```php
    Builder::macro('count', function () {
        $raw = $this->engine()->search($this);
        return (int) $raw['nbHits'];
    });
```

I made a small package to group useful macros. Feel free to submit feature request or contribute.
https://github.com/algolia/laravel-scout-algolia-macros

**Comment by danygiguere** [comment]
a way around it : $numberOfPosts = Post::search($search_text)->paginate(1); Then in your js this.numberOfPosts = response.data[1].total;

**Comment by driesvints** [comment]
You can use the macro as suggested above.

**Comment by lamualfa** [comment]
How about database driver?

**Comment by lamualfa** [comment]
I've implemented the `count` method for all Laravel Scout Drivers on this fork https://github.com/monoteam-co/laravel-scout. But, due to Semantic Versioning, the new `count` feature can't be added in a patch release.

##  This is a temporary solution for you

### 1. Edit the `repositories` field on your `composer.json` to:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/monoteam-co/laravel-scout.git"
    }
  ]
}
```
You can create a new one if the `repositories` field doesn't exist.

### 2. Edit the `laravel/scout` version on your `composer.json` to `10.x-dev`:

```json
{
  "require": {
    "laravel/scout": "10.x-dev"
  }
}
```

The `10.x-dev` means you tell the composer to install `laravel/scout` from https://github.com/monoteam-co/laravel-scout/tree/10.x instead.

### 3. Run `composer update` to update the `laravel/scout` package.

### The final `composer.json` file will look like this:

```json
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/monoteam-co/laravel-scout.git"
    }
  ],
  "require": {
    "laravel/scout": "10.x-dev"
  }
}
```

### Now, you can use `count` method in your Searchable Model

```php
model::search($keyword)->count();
```

### References

- https://getcomposer.org/doc/05-repositories.md#vcs
