### ISSUE TITLE
Highlighting results

### ISSUE THREAD

**Issue by plakhin** [laravel/scout#172]
I'm using default Algolia driver and want to highlight attributes in search results. I set up highlighting in Algloia UI but have no idea how to get hits or raw Algolia JSON answer sinnce Model::search('term')->get() returns only a collection of Eloquent models. Would appreciate any help.

**Comment by julienbourdeau** [comment]
So far the only way would be to use a custom engine extending AlgoliaEngine. You can either override `get()` so it returns the [raw results](https://github.com/laravel/scout/issues/114) from Algolia or override `map()` to set a `highlightResults` property to your model.

I don't think it will be added to scout since it's Algolia-specific. Otherwise you can have a look at [frontend search](https://community.algolia.com/instantsearch.js/).

**Comment by plakhin** [comment]
Thanks for response. I solved this using JS library on frontend.

**Comment by julienbourdeau** [comment]
Frontend search is much faster. It's the recommended way 💯

**Comment by plakhin** [comment]
Depends on the task, actually. For my application the right way is to use Scout for managing indices and Frontend search for displaying results. I also use Scout search for some complicated reports generation in backoffice.

**Comment by julienbourdeau** [comment]
In case people read this later, the `raw()` method was added, which returns the result from the engine. Highlighted values are available can be retrieved with this method.
