### ISSUE TITLE
Call to undefined method Laravel\Scout\Builder::whereBetween()

### ISSUE THREAD

**Issue by usmansharif525** [laravel/scout#186]
I am atrying to Exicute this query Spot::search($keyword)->where('type',$type)->whereBetween('latitude', [$latsw, $latne]) ->whereBetween('longitude', [$lonsw, $lonne])->take($limit)->get();

but it's not working
Please Help ASAP

**Comment by DMeganoski** [comment]
Because of the extra layer of data, the builder that is returned from the `search()` method is not the same that is returned when not using search. It is a much simpler version of builder, and not all methods of the eloquent builder are included in the scout builder. The method you are trying to use may work with eloquent, but it will not work with scout.

If you notice, there are several issues requesting functions that are part of eloquent be added to the scout builder, such as `whereIn()` and `count()`. Since each provider has different ways of handling the data, these can be tricky, and why they are not already implemented.

Since the where method of scout builder does not support an operand, you would have to use scout to search all records regardless of location, and then use the returned id's of the matching records to filter a second query. (this will create an extra query)

```php
$matching = Spot::search($keyword)->where('type',$type)->get()->pluck('id');
		$results = Spot::whereBetween('latitude', [$latsw, $latne]) ->whereBetween('longitude', [$lonsw, $lonne])->whereIn('id', $matching)->take($limit)->get();
```
On a side note, please highlight your code (in the future) to make it easier for others to read. It will increase your chances of getting a reply. https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by usmansharif525** [comment]
Thanksfor your replyit really helped and I will highlight my code next time.
