### ISSUE TITLE
"null" driver not settable via env variable

### ISSUE THREAD

**Issue by harrygr** [laravel/scout#34]
When trying to set the scout engine to the "null" implementation (e.g. say as a fallback for when no env variable exists: `'driver' => env('SCOUT_DRIVER', 'null')` or for tests) the string `"null"` is parsed into a php `null` value instead resulting in an instantiation error.

Suggest either renaming the null driver so something else like nullsearcher unless there is a way in phpunit.xml and .env it can be set as a string.

**Comment by morloderex** [comment]
Use double qoutes on the enviroment variable.

**Comment by harrygr** [comment]
How would one do that in a phpunit.xml file where the values are already between quotes?

    <env name="SCOUT_DRIVER" value="null" />

**Comment by dwightwatson** [comment]
Using double quotes on the environment variable doesn't work. I've been trying to do this to disable Laravel Scout in my test environment. Dotenv must take the string "null" to become null as well.

```
SCOUT_DRIVER="null"
```

```
>>> env('SCOUT_DRIVER');
=> null
```

My solution in the meantime has been to set the default driver to "null" in the `config/scout.php` file and then set it to "algolia" through an environment variable in production, but clearly this isn't great.

I suspect this issue will also affect the "null" Broadcast driver.

**Comment by talvbansal** [comment]
@dwightwatson I've managed to set my driver to null using your method as well as the `<env name="SCOUT_DRIVER" value='"null"' />` method too.

However my unit tests are **DIRE** slow after this:

**25seconds -> 7mins** 

Are slow unit tests something you're seeing too? 

It may well be because I'm using the [TntSearch driver](https://github.com/teamtnt/laravel-scout-tntsearch-driver) however I wanted to see if this is a scout issue or their implementation issue. Although using their native implementation not the scout wrapper has no impact on testing speed.

**Comment by harrygr** [comment]
@dwightwatson that's an OK suggestion but there's a problem when, for development, you have it set to "algolia" in your .env phpunit will fall back on that value if no value is set in phpunit.xml. Basically it means that if you have your local driver set to algolia there's no easy way to override that for tests. Will be a fine solution for CI though where you can just omit the driver env variable completely.

**Comment by thebrubaker** [comment]
I agree,it would be good to change this "null" option to "none" or "disable" or some equivalent that won't confuse .env to typecasting null from a string to a null value.

**Comment by talvbansal** [comment]
We've found a way around this that disables the auto indexing by default during unit tests, when we get around to writing the searching unit tests we can re enable it for those particular tests. 

I think we can close this issue now?

**Comment by dwightwatson** [comment]
You've found a solution using the PHPUnit configuration file, but this is still an issue with Scout configuration in general. I don't think this issue should be closed, and I think another option name should be chosen (or, support literal `null` as being the "null" driver).

**Comment by talvbansal** [comment]
Ahh totally sorry I thought I was responding to an issue on a different repo RE the scout implementation within that project sorry ignore my post above

**Comment by monsterdream** [comment]
Hello, I found a solution. You need to setup it in reversed way. Instead in you .env file put 
```
SCOUT_DRIVER=null 
```
and in config/Scout.php 
```
'driver' => env('SCOUT_DRIVER', 'algolia')
```
Put in .env
```
SCOUT_DRIVER=algolia
```
and in config/Scout.php 
```
'driver' => env('SCOUT_DRIVER', 'null')
```

**Comment by telkins** [comment]
Before I spend much more time on this, I figured I'd ask.

I have used the solution presented here for my application.  So, config/Scout.php defaults to the NULL driver and my .env is set to use "algolia".

My problem is unit testing (via PHPUnit).  How do I set SCOUT_DRIVER to the NULL driver for testing purposes.  The only solution I can think of is hackish: having config/Scout.php check to see if testing and then set it to the NUL driver....otherwise, business as usual.

Does anyone have any good suggestions/solutions?

**Comment by edcs** [comment]
I've had the same problem in my projects too - 'null' is a silly name to use for anything that goes through .env since Laravel turns it into a `null`. My workaround to get it to work nicely with PHPUnit is this (will only work on PHP 7.0 and above though):

`phpunit.xml`

```xml
<env name="SCOUT_DRIVER" value="null"/>
```

`config/scout.php`

```php
'driver' => env('SCOUT_DRIVER') ?? 'null',
```

I was considering doing a PR to fix this problem by renaming the 'null' driver to something else. Wondering if it's worth my time though as I don't want to spend a bunch of time on it for to be rejected.

**Comment by harrygr** [comment]
@edcs Your workaround is basically the same as the others suggest. Passing a 2nd argument into `env()` has the same effect.

This workaround fails however in the case where your local `.env` file has the driver set to something else (e.g. `alogolia`). Then, simply omitting `SCOUT_DRIVER' from phpunit.xml will not mean your tests will use the 'null' driver as laravel will fall back on the `.env` file and try to use algolia. This means that when you run your tests locally you'll be using the driver you set for development work.

It should be fine for CI though where you tend not to set the `SCOUT_DRIVER` at all.

**Comment by calebporzio** [comment]
Any solution here? It seems crazy that this hasn't been resolved...

**Comment by Pauly-** [comment]
@calebporzio You have to use double quotes on the SCOUT_DRIVER value. Like this:
<env name="SCOUT_DRIVER" value='"null"'/>

**Comment by calebporzio** [comment]
Thanks I think I just removed the reference to it and it defaults to null. Still not happy with the proposed solutions, but Oh well - thanks for the tip!

**Comment by chabib** [comment]
Try add this to your .env file just like what works in phpunit.xml file

`SCOUT_DRIVER='"null"'`

This way we don't have to 'hack' the scout config file

**Comment by mattstauffer** [comment]
This is no longer an issue; works fine after this:

https://github.com/laravel/scout/pull/224

**Comment by browner12** [comment]
documentation for the lazy:

https://laravel.com/docs/5.6/configuration#environment-variable-types
