### ISSUE TITLE
orderBy() Json column only sorts per paginated page

### ISSUE THREAD

**Issue by tanthammar** [laravel/scout#396]
- Scout Version: 7.2.1
- Laravel Version: 6.9.0
- PHP Version: 7.3.11
- Database Driver & Version: "teamtnt/laravel-scout-tntsearch-driver": "^7.2"
MySQL 5.7.24

### Description:
Using orderBy() on a Json column with paginate() gives a strange result.
Looks like it is sorting per paginated page and not across the entire search result.

### Steps To Reproduce:
```php
->search($search)
->orderBy('name->sv',  'asc')
->paginate()
````
Name column example:
```
{
	"en": "Demo Market",
	"sv": "Demo Marknad"
}
```

**Comment by driesvints** [comment]
Unfortunately we don't support the tntsearch driver, sorry.

**Comment by rodrigopedra** [comment]
Hi @tanthammar , there is some time I last worked with scout, but from memory I think the `->search()` method will return a Scout Builder instance, which have a `->orderBy()` method that will be applied after searching.

If you need to apply any bindings to the underlying database query Builder instance you should call the `->query()` method and pass a callback that will be applied before executing the search, something like this:

~~~php
->search($search)
->query(function ($query) {
    $query->orderBy('name->sv',  'asc'); // gets added to the underlying query builder
})
->paginate()
~~~

This way the `orderBy` would be applied on the database query builder before executing the search and thus before paginating. As the TNT Search driver is database based this should work.

I remember this because I got a similar problem and had to dig into Scout source code once to search for a solution. I got confused by the similar method names, but using this approach solved my problem at the time.

Hope it helps.
