### ISSUE TITLE
Jetstream, Nova + Scout - user.field_referencing_discrepency

### ISSUE THREAD

**Issue by StratMedia** [laravel/scout#604]
- Scout Version: Latest 
- Scout Driver: Database
-Jetstream Version: ^2.6
-Jetstream Stack: Livewire
-Uses Teams: Yes
-Laravel Version:8.83.5
-PHP Version: 8.1.2
-Database Driver & Version: MySql 8.0.27

### Description:
Installed fresh Laravel 8, Jetstream and Nova, in that order. Then installed Laravel/Scout.
All migrations up to date. 100% clean vanilla setup. No customisations.
So far only 1 user registered and user data is showing as expected in Nova.

### Steps To Reproduce:
Open Nova index page. Enter registered user name (in this case Bill) into top menu bar search field.
Throws a red overlay error message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.profile_photo_url' in 'where clause' (SQL: select * from users where (users.profile_photo_url like %Bill%) order by id desc).

There is no 'users.profile_photo_url' field. There is however a 'users.profile_photo_path' field. Dug around a little and discovered a) 10 x coded references to 'profile_photo_path` in vendor/laravel/jetstream and b) another 14 x coded references in same folder: vendor/laravel/jetstream. Ran composer remove laravel/scout - immediate problem solved. However, the above conflicting references persist.

Since I'm not entirely sure where the ultimate source of this conflict lies so submitted issues for Jetstream :
https://github.com/laravel/jetstream/issues/1004 and Nova https://github.com/laravel/nova-issues/issues/3781

**Comment by crynobone** [comment]
@StratMedia I already mention the solution to your issue https://github.com/laravel/nova-issues/issues/3781#issuecomment-1070919934 

Have you tried it?

**Comment by StratMedia** [comment]
Yes, I have implemented the workaround, which resolved the immediate problem. Thank you.

**Comment by driesvints** [comment]
I've dug into this more but I figured out this is specifically because you didn't define the searchable data (something that's noted in the docs). By default, the `toArray` will include appended data but this of course won't work with the DatabaseDriver. We could filter that out in the engine but given that you can just explicitly define the required columns to search I don't think we should.

`toArray` with Jetstream will, by default, *only* include the one appends value and nothing else. So by default, you won't be able to search anything anyway.

https://laravel.com/docs/9.x/scout#database-engine

<img width="705" alt="Screenshot 2022-03-18 at 13 57 39" src="https://user-images.githubusercontent.com/594614/159007088-8f36b040-8812-41cd-8fc7-6df8ade3b227.png">

**Comment by StratMedia** [comment]
Thank you for the feedback. Much appreciated.
