### ISSUE TITLE
no results from collection engine when scoutKeyName used

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [laravel/scout#627]
- Scout Version: 9.4.9
- Scout Driver: Collection
- Laravel Version: 9.17.0
- PHP Version: 8.1.6
- Database Driver & Version: -
- SDK Version (If using a third-party service): -
- Meilisearch CLI Version (If using Meilisearch): -

### Description:
when maping the results to instances of the given model via a lazy collection, collectionEngine uses $model->getKeyName to obtain the ids (Laravel\Scout\Engines\CollectionEngine.php:190)
later it searches them in \Laravel\Scout\Searchable::queryScoutModelsByIds:247 using $this->getScoutKeyName()
### Steps To Reproduce:
set scout key name in model and use collection engine

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by marcin-derlukiewicz** [comment]
i have some tests in this pr, but i don't know how i shoud handle qualified column names

**Comment by driesvints** [comment]
We're not looking to change this right now.
