### ISSUE TITLE
Sorting inside query() callback is not reflected in results.

### ISSUE THREAD

**Issue by PitchRE** [laravel/scout#637]
- Scout Version: ^9.4
- Scout Driver: MeiliSearch
- Laravel Version: ^9.11
- PHP Version: 8.1.6
- Database Driver & Version: ??? mysql  Ver 8.0.26
- SDK Version (If using a third-party service): #.#.#
- Meilisearch CLI Version (If using Meilisearch): 8.1.6

### Description:
orderBy seems to not affect results when using it inside query() callback.
Database queries are executed correctly but results doesn't reflect it.

### Steps To Reproduce:

```php
   $threads = Thread::search(request('search'))
            ->query(function ($query) {
                return $query->orderBy('id', 'desc');
            })->get(); 
            
         return $threads->pluck('id');
```
I would expect array of ids in descending order but it is not.
Sorting doesn't affects results.

![image](https://user-images.githubusercontent.com/45101591/181104669-0ee5a7db-f1b1-488f-b4aa-086953520406.png)

**Comment by driesvints** [comment]
@mmachatschek do you know what's going on here?

**Comment by mmachatschek** [comment]
@PitchRE @driesvints the query callback is used to retrieve e.g. additional fields but is not used for ordering results.

The search engine is responsible for ordering the results, therefore we have  `map()` methods in the corresponding engines that will reorder the results fetched from the database (the database will most definitely return a different order than the search engine).

To order the results, you need to call the `orderBy` method on the `Builder` instance instead of the eloquent query builder:

```php
$threads = Thread::search(request('search'))
            ->orderBy('id', 'desc')
            ->get(); 
```

@PitchRE if meilisearch raises an error in your case, then you will need to update the sortable attributes on you server. https://docs.meilisearch.com/reference/api/sortable_attributes.html

**Comment by driesvints** [comment]
Thanks @mmachatschek
