### ISSUE TITLE
Attribute `sku` is not sortable. Available sortable attributes are: ``."

### ISSUE THREAD

**Issue by caredev** [laravel/scout#645]
- Scout Version: 9.4.10
- Scout Driver: MeiliSearch 
- Laravel Version: 9.24.0
- PHP Version: 8.0.22
- Database Driver & Version: 0.28.1
- Meilisearch CLI Version (If using Meilisearch):  0.28.1

### Description:
After importing the model with `sail artisan scout:import` the items are not sortable.
#### This does not work
```
public function search(Request $request) {
        // Validate input $term
        $request->validate([
            'term' => 'required|string|max:255',
            'per_page' => 'nullable|integer|min:1|max:100',
        ]);
        $term = trim($request->input('term'));
        return Product::search($term)->orderBy('sku')->orderBy('name')->paginate($request->input('per_page', 10))
```

Throws the following exception.
```
"message": "Attribute `sku` is not sortable. Available sortable attributes are: ``.",
    "exception": "MeiliSearch\\Exceptions\\ApiException",
    "file": "/var/www/html/vendor/meilisearch/meilisearch-php/src/Http/Client.php",
    "line": 193,
```

**Comment by mmachatschek** [comment]
@caredev index settings (eg. ranking rules, sortable attributes, facets) on meilisearch need to be set separately.

In order to use sortable options with meili you have to update the sortable attributes https://docs.meilisearch.com/learn/advanced/sorting.html#configuring-meilisearch-for-sorting-at-search-time

This is not an issue on the Laravel Scout driver

**Comment by driesvints** [comment]
Thanks @mmachatschek

**Comment by caredev** [comment]
I thought it was implemented in laravel scout, sorry for that. Thank you.
