### ISSUE TITLE
Meilisearch Count

### ISSUE THREAD

**Issue by joaopalopes24** [laravel/scout#717]
- Scout Version: 10.0.2
- Scout Driver: Meilisearch
- Laravel Version: 10.4.1
- PHP Version: 8.2.4
- SDK Version (If using a third-party service): 1.0
- Meilisearch CLI Version (If using Meilisearch): 1.0.2

### Description:

Create Builder Macro in Provider, according to documetation:

https://laravel.com/docs/10.x/scout#builder-macros

![Screenshot from 2023-03-25 11-50-49](https://user-images.githubusercontent.com/45684782/227725439-39501af1-a03c-498a-a7ef-c158ea2ead53.png)

This error happens, image here:

![Screenshot from 2023-03-25 12-08-38](https://user-images.githubusercontent.com/45684782/227725602-a1c679d8-f603-41ce-a482-ded239b2b5f1.png)

### Steps To Reproduce:

Install Laravel Scout in project.

Run Meilisearch in v1.0.2.

Create Macro and run in some model, example:

`Integration::search($this->search)->count();`

**Comment by joaopalopes24** [comment]
After doing several tests, I believe the bug is within the Meiliseach SDK.

Check this PR: https://github.com/meilisearch/meilisearch-php/pull/482

**Comment by mmachatschek** [comment]
So the meilisearch-php SDK works fine here. Your bugfix is not needed as the underlying issue is in this example, missing defaults in the meilisearch engine of scout.

When you try to get the total count (as it is shown in the docs), the search params sent to meilisearch miss the `page/hitsPerPage` search params and therefore do not trigger an exhaustive search but rather an estimated search. The latter will not return the `totalHits` key in the raw search results.

@driesvints I found out that the `Builder::class` sets the phpdocs for the `Builder::limit` property to `int` but it should be `int|null`. In the meilisearch engine we expect an `int` so we can trigger the exhaustive search on meilisearch side. Easy fix would be to set an default value if `$build->limit` is `null`. What do you think?

**Comment by mmachatschek** [comment]
@joaopalopes24 you could set the limit yourself to work around this issue for now:

```php
Builder::macro('count', function () {
    $this->limit = 20;

    return $this->engine()->getTotalCount(
        $this->engine()->search($this)
    );
});
```

**Comment by driesvints** [comment]
@mmachatschek we'll have to add that to the upgrade guide if that's the case and also update the docs. 

But yeah setting a default value for Meilisearch could be a good idea. Also agree on updating the docblock.

**Comment by joaopalopes24** [comment]
@mmachatschek @driesvints Thanks for the answer. I'll add the limit here in the project and report back here.

**Comment by joaopalopes24** [comment]
I am closing this Issue.
