### ISSUE TITLE
Multisearch

### ISSUE THREAD

**Issue by vaniok010** [laravel/scout#730]
Are you planning to add a multisearch method to meilisearch?

**Comment by mmachatschek** [comment]
the current implementation of Laravel Scout doesn't support searching through multiple indexes. Algolia and Meilisearch support this feature.

This would need reimplementation of some parts of the library and a higher level abstractions that open up this functionality to different engines.

Searching through the https://github.com/algolia/scout-extended/ library I couldn't find issues on this topic so I think this is more of an edge case and should be implemented on the user side rather than here IMO

**Comment by driesvints** [comment]
We have no plans for this sorry.
