### ISSUE TITLE
Meilisearch return inconsistent results compared to database/algolia driver when using `take()` + `query()` + `paginate()`

### ISSUE THREAD

**Issue by crynobone** [laravel/scout#742]
### Scout Version

10.2.2

### Scout Driver

Meilisearch

### Laravel Version

10.12.0

### PHP Version

8.2.6

### Database Driver & Version

MySQL 8.0

### SDK Version

1.1.1

### Description

Given the following use-case:

```php
$queryCallback = fn ($query) => $query->where('created_at', '<', now()->subDays(1));

App\Models\User::search('example')->query($queryCallback)->take(200)->paginate(25);
```

It should search for `"example"` using Scout driver and take only `200` sample size, and from that `200` sample size query using Eloquent with only records created before `24 hours ago` and earlier, paginate the result using `25` records per page.

### Steps To Reproduce

You can refer to the reproducing repository: https://github.com/nova-issues/issue-5574/commit/b666ea2d9d8a96102797ca1b8468d6173281275d

1. Run `composer install`
2. Run `cp .env.example .env`
3. Run `php artisan key:generate`
4. Update Algolia credential on `.env` file.
5. Run `./vendor/bin/sail up -d`
6. Run `./vendor/bin/sail artisan migrate:fresh --seed`
7. Run `./vendor/bin/sail artisan scout:import App\\Models\\UserWithAlgolia`
7. Run `./vendor/bin/sail artisan scout:import App\\Models\\UserWithMeilisearch`
8. Access `/` route from the browser.

![image](https://github.com/laravel/scout/assets/172966/afde5003-79a2-4cce-8843-10277a0765a9)

**Comment by driesvints** [comment]
There are several issues about this like https://github.com/laravel/scout/issues/725 but I think the gist is that you can't use the `take` like this with the Meilisearch driver. I'm gonna page in @mmachatschek to see if he can provide a more detailed answer.

Also: are you sure you've rebuilt your search index after upgrade to Scout Meilisearch v1? Since some settings now use different keys.

I tried to send in a PR to the docs about this but probably badly phrased it: https://github.com/laravel/docs/pull/8704

**Comment by crynobone** [comment]
If that's the case then it not possible to use Scout + Meilisearch on Laravel Nova, this requires this combination to work correctly.

**Comment by mmachatschek** [comment]
@crynobone @driesvints 

with the query `example`, on meilisearch all results have the same relevancy, therefore the default meilisearch sorting will take effect. in this case. all results are ordered asc to the id (I guess this is due to the nature of adding documents to the index in ascending order)

Algolia returns the results with a different order. this is why you seemingly get a result with algolia but not with meilisearch:

Before adding a hard order on algolia:

![image](https://github.com/laravel/scout/assets/10237069/a4ea59cc-f06c-4ff3-b5f7-79e89e43a307)

after adding a sorting to algolia:

![image](https://github.com/laravel/scout/assets/10237069/99d3c16b-7c12-4778-ba63-e9bb70f01870)
![image](https://github.com/laravel/scout/assets/10237069/82425e87-e812-4e04-8a19-11ba23a009da)


so from my point of view, the behaviour is kind of the same from the implementation side but the default relevancy and sorting of the data is different.

**Comment by crynobone** [comment]
> with the query example, on meilisearch all results have the same relevancy, therefore the default meilisearch sorting will take effect. in this case. all results are ordered asc to the id (I guess this is due to the nature of adding documents to the index in ascending order)

But still, the total items in the index is only 26 records, and using `->take(200)` should already account for this. 

> Algolia returns the results with a different order. this is why you seemingly get a result with algolia but not with meilisearch

I increased the total record to 200 and algolia still able to get the correct record:

![image](https://github.com/laravel/scout/assets/172966/2d6cf62f-7e98-404c-8f96-1b3f62acdc20)

![image](https://github.com/laravel/scout/assets/172966/671032b5-29e1-413d-a1d8-758dea49387f)

**Comment by mmachatschek** [comment]
@crynobone still this happens because Algolia returns a different order of results than meilisearch, thats why you have a difference in the search results you are seeing.

If we would flip the seeder on your example repo, so that the `Test User` is created prior to the other 199 items you would get results with meilisearch as well.

> But still, the total items in the index is only 26 records, and using ->take(200) should already account for this.

The `take()` in this case doesn't really do anything because `->paginate()` is used and therefore only 25 items are loaded from the search engine

the `->query` will be applied *after* the results are returned by the search engine. If you want to prefilter the results. you would need to do `->search('example', fn() => {// customize the query to the engine})` on the engine side.

This is also stated on the docs page https://laravel.com/docs/10.x/scout#:~:text=Since%20this%20callback,for%20%22filtering%22%20results

A solution to your problem could be:

1. loading all items from the search engine `User::search('example')->take(10000)->query(xxx)->get()`
2. transform the items into a eloquent query
3. paginate the eloquent query

**Comment by crynobone** [comment]
> The take() in this case doesn't really do anything because ->paginate() is used and therefore only 25 items are loaded from the search engine

In Algolia (and the way we made the Laravel Nova + Scout + Algolia) integration before are:

`App\Models\User::search('example')->query($queryCallback)->take(200)->paginate(25);`

1. Search from the index with the keyword "example" with a hard limit of `200` records.
2. Get all the IDs from index found from step 1 as key https://github.com/laravel/scout/blob/9f64e8e58f1a982dccab150a9f53179d32fbe566/src/Engines/AlgoliaEngine.php#L199-L216
3. Use eloquent to generate a new query with `whereKey()` matching the IDs from index and apply `$queryCallback` https://github.com/laravel/scout/blob/9f64e8e58f1a982dccab150a9f53179d32fbe566/src/Searchable.php#L247-L263
4. Then make pagination from step 3 https://github.com/laravel/scout/blob/9f64e8e58f1a982dccab150a9f53179d32fbe566/src/Builder.php#L405-L407

**Comment by simon-roland** [comment]
> 1. Search from the index with the keyword "example" with a hard limit of `200` records.

@crynobone  I think this is where the problem occurs. Are you sure that this search is not paginated before the filter is applied?

It does not seem like this issue is limited to Meilisearch, the order of results from the engine used determines the result.

Its like I said in https://github.com/laravel/nova-issues/issues/5574

> It seems, that if the filter does not include any of the results from the first page, then no results are shown.

**Comment by driesvints** [comment]
Closing this as this is an implementation issue in Nova.
