### ISSUE TITLE
Add Support for Manticore Search

### ISSUE THREAD

**Issue by eservercom** [laravel/scout#832]
Hi Laravel Scout Team!

I'm using Laravel and Manticore Search in a [real project](https://e-server.com.ua/) and noticed there's no out-of-the-box solution for integrating Manticore Search with Laravel Scout. It would be awesome to have this support.

Why it's needed:

Real-time: Manticore Search supports real-time indexing and searching, which is great for fresh data.
High performance: It handles large volumes of data and fast searches really well.
Rich query language: Supports complex search queries, filtering, and aggregations.
Scalability: Easily scales horizontally for big projects.
Proposal:

Develop a driver for Manticore Search in Laravel Scout.
Ensure compatibility with existing Scout functionalities like indexing and searching models.
Add documentation and examples for a quick start.
References:

[Manticore Search Documentation](https://manual.manticoresearch.com/)

I hope this integration helps many developers, just like it would help me. Thanks for considering!

**Comment by driesvints** [comment]
Thanks. Right now we don't have plans for new adapters sorry.

**Comment by Sawaiii** [comment]
nice

**Comment by itaginsexordium** [comment]
> Thanks. Right now we don't have plans for new adapters sorry.


Why not? This would be very useful since the Manticore has been developing very well over the last couple of years. In the community, the Manticore team approaches meetings with the attitude of "[We are ready to develop and support if the guys from Laravel Scout integrate it in the end.](https://t.me/manticore_chat/7198/12688)"


[Interest survey in active community chat on manticore](https://t.me/manticore_chat/1/12209) 
although the chat is not always very active, there is interest


I would like to get an adequate tool for this, but I constantly have to reinvent the wheel or search in communities where I sometimes encounter incomprehensible packages at the /b(nonsense) level.

If there is any possibility to do this, please let us know, and we will do it as a community.
