### ISSUE TITLE
Paginate not working

### ISSUE THREAD

**Issue by repirisyan** [laravel/scout#886]
### Scout Version

10.11.7

### Scout Driver

Algolia

### Laravel Version

11.31.0

### PHP Version

8.2.24

### Database Driver & Version

Mysql 8.0.33

### Description

I am using algolia search for scout, and do paginate, the paginate is can be produce but it seem like show all the data

### Steps To Reproduce

News::search('')->orderBy('date_news','desc')->paginate(6)

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
